[project]
name = "dna-lm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ruff>=0.15.1",
    "torch>=2.10.0",
    "wandb>=0.25.0",
]
